### ISSUE TITLE
Button generated by "filepicker" directive lacks style

### ISSUE THREAD

**Issue by rbwinslow** [krystiangw/angular-filepicker#1]
"Pick file" buttons generated by the base FilePicker script (using INPUT TYPE="filepicker") have a "fp__btn" class that provides all of the nice Bootstrap-based style. The button you get from combining the "filepicker" directive (as illustrated in this project's README) with the FilePicker V2 script is an unstyled button; no "fp__btn" class.

I'm using angular-filepicker in conjunction with Angular JS 1.3.19. I'm including both the V2 script from the API site and the angular_filepicker script near the bottom of the main HTML page (index.html), and using the directive inside a template nested two-deep, which appears earlier in terms of DOM order and later in terms of chronology (it's loaded as part of a wizard the user navigates).

Examining the V2 script served right now by the filepicker API site, I don't see the "constructWidget" function that this directive is invoking, so there's some more opaque cleverness going on.

**Comment by krystiangw** [comment]
Widget set 'fp__btn' class only if there is no other class specified. However angular applies `ng-isolate-scope` class to any element for which a new isolate scope is defined. 

The simplest workaround would be set `data-fp-button-class="fp__btn"` directive attribute.
