### ISSUE TITLE
Angular 2 Support

### ISSUE THREAD

**Issue by Mahaswami** [krystiangw/angular-filepicker#13]
It would be great to support Angular 2 for the new projects we are using FileStack for.

Could you please share a timeline when this can be done? We can contribute to this change at least partly.

**Comment by cogKnitter** [comment]
We would be happy to work with you on this. I will discuss with our team and tag you when we have a repo launched for Angular 2. 
Thanks for reaching out @Mahaswami

**Comment by AndrzejSala** [comment]
@Mahaswami 
Hi,
You can find a new version of the filestack angular module at https://github.com/filestack/filestack-angular

This repo is for now deprecated and we have not plans to update it.
