### ISSUE TITLE
FilePicker Preview Does Not Generate the Appropriate Iframe

### ISSUE THREAD

**Issue by stephenycchang** [krystiangw/angular-filepicker#2]
Based on the docs, I should use this markup.

<div filepicker-preview url="previewUrlExample" style="width:90%; height:500px"></div>

I have in my code:
var foo = angular.module('foo', ['angular-filepicker'])
Included the regular JS API library as well.  

In my view, just testing it, since fetching the file through angular doesn't work, I'm trying to get it by passing it a real source directly:

<div type="filepicker-preview" url="https://www.filepicker.io/api/file/foo" style="width:90%; height:500px"></div>

foo is replaced here but is an actual filepicker file. 
I've tried replacing /file with /preview, both don't work. 
i gave it a type="filepicker-preview" as i believe the one on the docs is incorrect. 

Inspecting the element, the iframe gets created, but the url always either doesn't show up or undefined. So the Filepicker preview widget doesn't show at all. 

Any ideas why?

**Comment by krystiangw** [comment]
@stephenycchang If you are using [filepicker-angular](https://github.com/filepicker/filepicker-angular) library you should use `filepicker-preview` directive to generate viewer. Example code:
`<div filepicker-preview url="previewUrlExample" style="width:90%; height:500px"></div>`

where `previewUrlExample` is scope url variable.

Please look at [demo page code](https://github.com/filepicker/filepicker-angular/blob/develop/demo/templates/examples.html#L69) to see how to use it.
There is also [live demo page](http://filepicker.github.io/filepicker-angular/demo/index.html#/).

**Comment by stephenycchang** [comment]
@krystiangw if you check your live demo page, the Filepicker preview widget throws a 

XMLHttpRequest cannot load https://d2hbo3cbwd28c.cloudfront.net/098e8a6/preview/locale/locale.properties. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.filepicker.io' is therefore not allowed access.

This sometimes breaks the functionalities such as zoom in etc.

Is there a fix for that?

**Comment by krystiangw** [comment]
@stephenycchang You are right, one of the assets (i18n file) fail to load due to CORS restrictions. However it does not affect any of the preview widget functionality. You can see the same error if you open preview widget directly in a browser: https://www.filepicker.io/api/preview/L78eRqmFQYuZoozoddbX

So the issue  is not caused by the filepicker-angular library.
