### ISSUE TITLE
how do I change the button text?

### ISSUE THREAD

**Issue by connor11528** [krystiangw/angular-filepicker#5]
I have an input field using the directive. The text always says "Pick File". How can I change the text of the button to something else? I use `data-fp-button-class` to apply a custom class.

Here is my html:

```
<input filepicker type="filepicker" data-fp-services="computer,facebook,webcam,box" on-success="pickResults=event.fpfile" data-fp-button-class="btn btn-success" />
```

**Comment by krystiangw** [comment]
Use  `data-fp-button-text` attribute.  It accepts text 
`data-fp-button-text="My super button!"`
or angular expression: 
 `data-fp-button-text="{{ buttonText }}"`

See all options [in the docs](https://www.filestack.com/docs/file-ingestion/widgets/pick).

**Comment by connor11528** [comment]
Cool! And to add a little font awesome icon it accepts html:

```
<input filepicker 
    type="filepicker" 
    data-fp-services="computer,facebook,webcam,box" 
    on-success="onSuccess(event.fpfile)" 
    data-fp-button-class="btn btn-success btn-lg"
    data-fp-button-text='<i class="fa fa-3 fa-cloud-upload"></i> Upload a file!' />
```
